package corbaJavaGenerated.CounterCORBA;

/**
* corbaJavaGenerated/CounterCORBA/CounterInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterInterface.idl
* Saturday, October 17, 2015 1:55:24 PM GMT
*/

public final class CounterInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaJavaGenerated.CounterCORBA.CounterInterface value = null;

  public CounterInterfaceHolder ()
  {
  }

  public CounterInterfaceHolder (corbaJavaGenerated.CounterCORBA.CounterInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaJavaGenerated.CounterCORBA.CounterInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaJavaGenerated.CounterCORBA.CounterInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaJavaGenerated.CounterCORBA.CounterInterfaceHelper.type ();
  }

}
