package corbaJavaGenerated.CounterCORBA;


/**
* corbaJavaGenerated/CounterCORBA/CounterInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterInterface.idl
* Wednesday, October 21, 2015 11:52:34 PM GMT
*/

public interface CounterInterfaceOperations 
{
  void incrementCounter ();
  int getCount ();
  void printCounter ();
} // interface CounterInterfaceOperations
