package corbaJavaGenerated.CounterCORBA;


/**
* corbaJavaGenerated/CounterCORBA/CounterInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterInterface.idl
* Saturday, October 17, 2015 1:55:24 PM GMT
*/

public interface CounterInterfaceOperations 
{
  void incrementCounter ();
  int getCount ();
  void printCounter ();
} // interface CounterInterfaceOperations
