package corbaJavaGenerated.CounterCORBA;


/**
* corbaJavaGenerated/CounterCORBA/CounterInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterInterface.idl
* Wednesday, October 21, 2015 11:52:34 PM GMT
*/

public abstract class CounterInterfacePOA extends org.omg.PortableServer.Servant
 implements corbaJavaGenerated.CounterCORBA.CounterInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("incrementCounter", new java.lang.Integer (0));
    _methods.put ("getCount", new java.lang.Integer (1));
    _methods.put ("printCounter", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CounterCORBA/CounterInterface/incrementCounter
       {
         this.incrementCounter ();
         out = $rh.createReply();
         break;
       }

       case 1:  // CounterCORBA/CounterInterface/getCount
       {
         int $result = (int)0;
         $result = this.getCount ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // CounterCORBA/CounterInterface/printCounter
       {
         this.printCounter ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CounterCORBA/CounterInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CounterInterface _this() 
  {
    return CounterInterfaceHelper.narrow(
    super._this_object());
  }

  public CounterInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CounterInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CounterInterfacePOA
